### ISSUE TITLE
Write tests for container template

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-templates#10]
Tests to be created:
- [ ] _validate_input: 
  - test exception is raised when data is not correct
  -  test nothing is raised when data is correct
- [ ] node_sal
  - test self._node is properly set
- [ ] container_sal
  - test `self.install` is called is container doesn't exists
  - test return value when container exists
- [ ] install
  - method failes if state of node is not correct
  - test exception is raise if self.node_sal is None
  - test `self.node_sal.containers.get` is called
  - test state of the service is correct: actions install and start are ok
- [ ] start:
  - test early return when node_name != self.data['node']
  - test state is update properly
  -  test `self.container_sal.start` is called
- [ ] stop:
  - same as start

**Comment by serboctor** [comment]
Fixed by https://github.com/zero-os/0-templates/pull/17
