### ISSUE TITLE
write tests for hypervisor template

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-templates#12]
test to be created 
- [ ] _validate_input:
  - test exception is raise when data not correct
  - test exception not raise when data is correct
- [ ] node_sale
  - test `self._node` is set
- [ ] create
  - test `self.node_sal.client.kvm.create` is called
  - test seld.data['uid'] is set properly
- [ ] destroy, shutdown, pause, resume, reboot, reset
  - test `self.node_sal.client.kvm.{method}` not called when 'uid' not in `self.data`
  - test `self.node_sal.client.kvm.{method}`` us called when 'uid' in `self.data`
  - test 'uid' is not in self.data anymore (for detroy only)

**Comment by serboctor** [comment]
https://github.com/zero-os/0-templates/pull/17
