### ISSUE TITLE
namspace password can't be changed from yes to no

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-templates#147]
## Scenario
1- Create a zerodb service and install it using dsl 
2- Get namespace_info, password=no
3- Set Namespace password to yes and get namespace info password = yes
4- Set Namespace password to "no"  and get namespace

![issue11](https://user-images.githubusercontent.com/15011431/41601210-200cdca2-73d8-11e8-8ab1-a5e80c02192f.png)

## Actual Result 
password still equals yes

**Comment by serboctor** [comment]
'yes' indicates that there is a password, it doesn't mean that the password itself is `yes`. So when you set it to `no`, you are not disabling the password, you are changing the current value to be `no`, so of course the result of the info will still be `yes` because the namespace has a password.
