### ISSUE TITLE
Make the deployment of the 0-db on top of each disk during node install optional

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-templates#69]
This commit disable the deployment of the 0-db during node install. We need a flag that allow to choose if we want to deploy 0-db or not

**Comment by serboctor** [comment]
Changes for this ticket are on this branch https://github.com/zero-os/0-templates/tree/deploy-zdb but @zaibon said the whole node-zdb flow might have to be reworked.

**Comment by zaibon** [comment]
It is time to revive this issue. We're getting close to have all the primitives templates.
But now we still don't have a way to properly deploy zerodb's on a node using the 0-robot.
The zerodb template expect a `path` argument. although, there is no way to chose/prepare a disk to be used by zerodb using the robot, so basically we can't deploy any zerodb.

I see 2 way of doing things here:

1. We add a method on the node service that allow to ask for a disk/path based on its type (hdd,ssd) and size. This method would look on the node, and find the best disk to used based on the requirements.

2. The zerodb template itself hold the logic to prepare and choose the disk it will be using.

**Comment by serboctor** [comment]
Final implementation:
We added action `create_zdb_namespace` in the node template, where you specify the size you want to reserve and the disk type, the logic creates the namespace and determines on which zerodb it should be created.
