### ISSUE TITLE
nzrobot: Node service need to be usable from the node robot

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-templates#76]
currently the node takes redisAddr, and redisPassword.
Maybe instead we should just consume the zeroos-client cause the node booted with node robot have a zeroos that connect to the local redis unix socket.

Also, need to review the install, make sure it match with how the node robot works.

**Comment by serboctor** [comment]
@zaibon what do you mean by "match with how the node robot works"? how does the node robot work?

> Maybe instead we should just consume the zeroos-client cause the node booted with node robot have a zeroos that connect to the local redis unix socket.

what's the name of the configured zeroo-client isntance that the node boots with? may be we can fix it to `main` and in the node template just use the `main` instance? or does the zeroos-client instance follow the the naming convention of using the macaddress?

**Comment by zaibon** [comment]
the instance of the zero-os client is `local`, this is hardcoded, so we should be able to indeed use it like that

**Comment by serboctor** [comment]
If some node actions will be performed from the node robot, and other from a higher layer, shouldn't we have two separate templates?

Also, if the node reboot will be executed from the node robot, does that mean that the container and vm templates should be adapted too? because we stop/start vm/containers before/after the reboot.

**Comment by zaibon** [comment]
> If some node actions will be performed from the node robot, and other from a higher layer, shouldn't we have two separate templates?

What are you thinking of ? what would you put where ?

> Also, if the node reboot will be executed from the node robot, does that mean that the container and vm templates should be adapted too? because we stop/start vm/containers before/after the reboot.

What is needed to be adapted to work with node robot ?
