### ISSUE TITLE
Review zerodb templates

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-templates#77]
I think we can improve this template a bit.
The 4 schema attributes can be removed I think:
- nodeMountPoint
- containerMountPoint
- dataDir
- indexDix

We don't have to let the user choose where to mount the disk in the container, that can be an hardoced location.
The only think this templates should know about, is the host path that it needs to mount into the container.

If we think bigger picture, the service that will provision a zerodb, will only ask the user what type of disk he wants (HDD, SSD), the  container mountpoint etc is just implementation detail that should not be exposed to the end user

**Comment by zaibon** [comment]
Proposed new schema:

- `mode`: a value from enum Mode representing the 0-db mode.
- `sync`: boolean indicating whether all write should be sync'd or not.
- `node`: reference to the node running the zerdb container

Mode enum:
- `user`: the default user key-value mode.
- `seq`: sequential keys generated.
- `direct`: direct position by key.

Actions:
- `start`: starts the container and the 0-db process. 
- `stop`: stops the 0-db process.
- `namespace_create`: create a new namespace. Only admin can do this.
- `namespace_info`: returns basic information about a namespace
- `namespace_list`: returns an array of all available namespaces.
- `namespace_set`: change a namespace setting/property. Only admin can do this.
- `free_space`: return the amount of storage space still available for reservation

With this schema and action, the robot that will create a namespace to reserve storage has all the information he needs to decided on which zero-db to create the namespace.

**Comment by zaibon** [comment]
I also think we should create a zdb-namespace template.
Cause namespace is really the primitives we want to provide and we can't just let any client manage the zero-db itself, what they buy is a namespace and that the only think the client should be able to manage

**Comment by serboctor** [comment]
I'll close this, meanwhile, here is thenamespace template task  https://github.com/zero-os/0-templates/issues/90
